name: Update AED Wait Time Data

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python aed_wait_time_scraper.py
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: script-logs
        path: script.log
        retention-days: 7
